language: android
android:
  components:
    - tools-28
    - build-tools-28.0.2
    - android-28
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-27"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
  - sed -i "\$a Guardian_ApiKey=$Guardian_ApiKey" ./gradle.properties
  - ./gradlew assembleDebug